version: "3.7"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    networks: 
      - default
    ports:
    - "8080:8080"
volumes:
  data:


